using GuysNight.LethalCompanyMod.BalancedItems.Models;

namespace GuysNight.LethalCompanyMod.BalancedItems {
	public static class ItemOverridesContainer {
		public static ItemPropertyOverride[] ItemOverrides { get; } = {
			//spawned loot items
			new ItemPropertyOverride("7Ball", 0.5f),
			new ItemPropertyOverride("Airhorn", 1.5f),
			new ItemPropertyOverride("Bell", 5),
			new ItemPropertyOverride("BigBolt", 7),
			new ItemPropertyOverride("BottleBin"),
			new ItemPropertyOverride("Brush", 1),
			new ItemPropertyOverride("Candy", 1),
			new ItemPropertyOverride("CashReg", 20),
			new ItemPropertyOverride("ChemicalJug", 20),
			new ItemPropertyOverride("Clipboard", 0.1f),
			new ItemPropertyOverride("ClownHorn", 1),
			new ItemPropertyOverride("Cog1", 25),
			new ItemPropertyOverride("ComedyMask", 2),
			new ItemPropertyOverride("Dentures", 1.5f),
			new ItemPropertyOverride("DiyFlashbang", 1.5f),
			new ItemPropertyOverride("DustPan", 1),
			new ItemPropertyOverride("EggBeater", 0.5f),
			new ItemPropertyOverride("EnginePart1", 30),
			new ItemPropertyOverride("FancyCup", 4),
			new ItemPropertyOverride("FancyLamp", 10),
			new ItemPropertyOverride("FancyPainting"),
			new ItemPropertyOverride("FishTestProp", 0.5f),
			new ItemPropertyOverride("FlashLaserPointer", 1),
			new ItemPropertyOverride("Flask", 2),
			new ItemPropertyOverride("GiftBox"),
			new ItemPropertyOverride("GoldBar", 27.5f),
			new ItemPropertyOverride("Hairdryer"),
			new ItemPropertyOverride("Key", 0.1f),
			new ItemPropertyOverride("LungApparatus", 50),
			new ItemPropertyOverride("MagnifyingGlass", 4),
			new ItemPropertyOverride("MetalSheet", 7),
			new ItemPropertyOverride("MoldPan", 3),
			new ItemPropertyOverride("Mug", 2),
			new ItemPropertyOverride("PerfumeBottle", 0.5f),
			new ItemPropertyOverride("Phone"),
			new ItemPropertyOverride("PickleJar", 3),
			new ItemPropertyOverride("PillBottle", 1),
			new ItemPropertyOverride("Ragdoll", 100),
			new ItemPropertyOverride("RedLocustHive", 0.5f),
			new ItemPropertyOverride("Remote", 1),
			new ItemPropertyOverride("Ring", 0.2f),
			new ItemPropertyOverride("RobotToy", 5),
			new ItemPropertyOverride("RubberDuck", 0.5f),
			new ItemPropertyOverride("Shotgun", 15),
			new ItemPropertyOverride("SodaCanRed", 0.5f),
			new ItemPropertyOverride("SteeringWheel", 5),
			new ItemPropertyOverride("StickyNote", 0.1f),
			new ItemPropertyOverride("StopSign", 6),
			new ItemPropertyOverride("TeaKettle", 5),
			new ItemPropertyOverride("Toothpaste", 1),
			new ItemPropertyOverride("ToyCube", 1),
			new ItemPropertyOverride("TragedyMask", 2),
			new ItemPropertyOverride("WhoopieCushion", 0.5f),
			new ItemPropertyOverride("YieldSign", 6),

			//purchased items
			new ItemPropertyOverride("Boombox", 10),
			new ItemPropertyOverride("ExtensionLadder", 10),
			new ItemPropertyOverride("Flashlight", 2),
			new ItemPropertyOverride("Jetpack"),
			new ItemPropertyOverride("LockPicker", 10),
			new ItemPropertyOverride("ProFlashlight", 2),
			new ItemPropertyOverride("RadarBooster"),
			new ItemPropertyOverride("Shovel", 5),
			new ItemPropertyOverride("SprayPaint", 1),
			new ItemPropertyOverride("StunGrenade", 2),
			new ItemPropertyOverride("TZPInhalant", 1),
			new ItemPropertyOverride("WalkieTalkie", 2),
			new ItemPropertyOverride("ZapGun", 7)
		};
	}
}