using System.Collections.Generic;
using GuysNight.LethalCompanyMod.BalancedItems.Models;

namespace GuysNight.LethalCompanyMod.BalancedItems {
	public static class ItemOverridesContainer {
		public static Dictionary<string, ItemPropertyOverride> ItemOverrides { get; } = new Dictionary<string, ItemPropertyOverride> {
			//spawned scrap items
			{ "7Ball", new ItemPropertyOverride(0.5f, 135) },
			{ "Airhorn", new ItemPropertyOverride(1.5f, 155) },
			{ "Bell", new ItemPropertyOverride(5f, 160) },
			{ "BigBolt", new ItemPropertyOverride(7f, 65) },
			{ "BottleBin", new ItemPropertyOverride(125) },
			{ "Brush", new ItemPropertyOverride(1f, 55) },
			{ "Candy", new ItemPropertyOverride(1f, 53) },
			{ "CashRegister", new ItemPropertyOverride(20f, 300) },
			{ "ChemicalJug", new ItemPropertyOverride(20f, 145) },
			{ "ClownHorn", new ItemPropertyOverride(1f, 155) },
			{ "Cog1", new ItemPropertyOverride(25f, 115) },
			{ "ComedyMask", new ItemPropertyOverride(2f, 100) },
			{ "Dentures", new ItemPropertyOverride(1.5f, 180) },
			{ "DiyFlashbang", new ItemPropertyOverride(1.5f, 48) },
			{ "DustPan", new ItemPropertyOverride(1f, 55) },
			{ "EggBeater", new ItemPropertyOverride(0.5f, 70) },
			{ "EnginePart1", new ItemPropertyOverride(30f, 95) },
			{ "FancyCup", new ItemPropertyOverride(4f, 150) },
			{ "FancyLamp", new ItemPropertyOverride(10f, 235) },
			{ "FancyPainting", new ItemPropertyOverride(230) },
			{ "FishTestProp", new ItemPropertyOverride(0.5f, 85) },
			{ "FlashLaserPointer", new ItemPropertyOverride(1f, 165) },
			{ "Flask", new ItemPropertyOverride(2f, 75) },
			{ "GiftBox", new ItemPropertyOverride(50) },
			{ "GoldBar", new ItemPropertyOverride(27.5f, 390) },
			{ "Hairdryer", new ItemPropertyOverride(200) },
			{ "LungApparatus", new ItemPropertyOverride(50f, 80) },
			{ "MagnifyingGlass", new ItemPropertyOverride(4f, 130) },
			{ "MetalSheet", new ItemPropertyOverride(7f, 40) },
			{ "MoldPan", new ItemPropertyOverride(3f, 65) },
			{ "Mug", new ItemPropertyOverride(2f, 115) },
			{ "PerfumeBottle", new ItemPropertyOverride(0.5f, 190) },
			{ "Phone", new ItemPropertyOverride(140) },
			{ "PickleJar", new ItemPropertyOverride(3f, 115) },
			{ "PillBottle", new ItemPropertyOverride(1f, 70) },
			{ "Remote", new ItemPropertyOverride(1f, 85) },
			{ "Ring", new ItemPropertyOverride(0.2f, 165) },
			{ "RobotToy", new ItemPropertyOverride(5f, 180) },
			{ "RubberDuck", new ItemPropertyOverride(0.5f, 128) },
			{ "SodaCanRed", new ItemPropertyOverride(0.5f, 135) },
			{ "SteeringWheel", new ItemPropertyOverride(5f, 60) },
			{ "StopSign", new ItemPropertyOverride(6f, 90) },
			{ "TeaKettle", new ItemPropertyOverride(5f, 110) },
			{ "Toothpaste", new ItemPropertyOverride(1f, 78) },
			{ "ToyCube", new ItemPropertyOverride(1f, 85) },
			{ "TragedyMask", new ItemPropertyOverride(2f, 100) },
			{ "WhoopieCushion", new ItemPropertyOverride(0.5f, 33) },
			{ "YieldSign", new ItemPropertyOverride(6f, 90) },

			//spawned non-scrap items
			{ "Clipboard", new ItemPropertyOverride(0.1f) },
			{ "Key", new ItemPropertyOverride(0.1f) },
			{ "Ragdoll", new ItemPropertyOverride(100f) },
			{ "RedLocustHive", new ItemPropertyOverride(0.5f, 115) },
			{ "Shotgun", new ItemPropertyOverride(15f) },
			{ "StickyNote", new ItemPropertyOverride(0.1f) },

			//purchased equipment
			{ "Boombox", new ItemPropertyOverride(10f) },
			{ "ExtensionLadder", new ItemPropertyOverride(10f) },
			{ "Flashlight", new ItemPropertyOverride(2f) },
			{ "Jetpack", new ItemPropertyOverride() },
			{ "LockPicker", new ItemPropertyOverride(10f) },
			{ "ProFlashlight", new ItemPropertyOverride(2f) },
			{ "RadarBooster", new ItemPropertyOverride() },
			{ "Shovel", new ItemPropertyOverride(5f) },
			{ "SprayPaint", new ItemPropertyOverride(1f) },
			{ "StunGrenade", new ItemPropertyOverride(2f) },
			{ "TZPInhalant", new ItemPropertyOverride(1f) },
			{ "WalkieTalkie", new ItemPropertyOverride(2f) },
			{ "ZapGun", new ItemPropertyOverride(7f) }
		};
	}
}